version: '3'
services:
  roscore:
    image: ros:melodic-robot-bionic
    command: roscore
    network_mode: "host"
    environment:
      - ROS_IP
  ros:
    build: aion_control/
    image: aion_control
    devices:
      - "/dev/ttyACM0:/dev/mavlink"
      - "/dev/ttyUSB0:/dev/rplidar"
    network_mode: "host"
    environment:
      - ROS_IP
  realsense:
    build: aion_realsense/
    image: realsense_arm
    volumes:
      - /dev/video/
    privileged: true
    network_mode: "host"
    environment:
      - ROS_IP
    command: ["bash", "-c", "source /catkin_ws/devel/setup.bash && roslaunch --wait realsense2_camera rs_camera.launch filters:=pointcloud"]
